// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'field': string;
  'modal__content': string;
  'modal__inner': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
