// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  modal__content: string;
  modal__inner: string;
}
export const cssExports: CssExports;
export default cssExports;
