// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comments': string;
  'container_centered': string;
  'content': string;
  'content__body': string;
  'content__title': string;
  'field': string;
}
export const cssExports: CssExports;
export default cssExports;
