// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button_full': string;
  'link_full': string;
  'ticketList': string;
  'ticketList__content': string;
}
export const cssExports: CssExports;
export default cssExports;
