// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__actions': string;
  'card__actions_bottom': string;
  'card__actions_top': string;
  'card__raw': string;
  'card__tags': string;
}
export const cssExports: CssExports;
export default cssExports;
